### ISSUE TITLE
Progress   

### ISSUE THREAD

**Issue by Chan0369** [Chan0369/simple-chat-app#6]
# Progress
- [x] Paper Wireframes
  - [x] 404 page
  - [x] Chat (main) page
  - [x] Members List
  - [x] Notifications
    - [x] Joined
    - [x] Left

# Issues
Completed:

- Login
- Main page
- Member list

@JamAbalos  @bonniecampbell  @ericadamski

**Comment by Chan0369** [comment]
# Positives :+1:

+ ...
+ ...
+ ...

# Improvements :star:

+ ...
+ ...
+ ...

# Request for Feedback :ear:

+ ...
+ ...
+ ...

**Comment by JamAbalos** [comment]
# Positives :+1:

+ Everything went well
+ Group stayed on task
+ Group finished all assigned task
+ Group is awesome

# Improvements :star:

+ Some features are not editable
+ Simplify some features

# Request for Feedback :ear:

+ What can and can't we edit?

**Comment by bonniecampbell** [comment]
# Positives :+1:
 
We we're all on the same page about what we wanted overall. When we brought together our individual wireframes, all of our idea's came together nicely. We were able to work together as a team and decide what we liked and didn't like without any conflict. 

# Improvements :star:

We all had great idea's, but we might need to simplify everything moving forward depending on our capabilities and what can be included and changed in the project. 

# Request for Feedback :ear:

Our biggest question is what are we able to add or edit within the project? A few of our idea's were declined because they just wouldn't be possible according to how the code is already prepared.

**Comment by Chan0369** [comment]
# Positives :+1:

+ worked well together, had similar ideas 
+ finish the assigned work
+ no conflicts

# Improvements :star:

+ we had good ides, but might be too complicated to code
+ simply the features 

# Request for Feedback :ear:

+ What can we add or edit for our simple chat?

**Comment by ericadamski** [comment]
We will discuss what you can edit in class this week! Great job!
